#### You can download the full data from [Kaggle](https://www.kaggle.com/mlg-ulb/creditcardfraud)


In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time
from sklearn.metrics import confusion_matrix

data = pd.read_csv('creditcard.csv')

print('data loaded')

data loaded


In [2]:
x = data.iloc[:,1:-1]
y = data.iloc[:,-1]

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=0)

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train = sc.fit_transform(x_train)
X_test = sc.fit_transform(x_test)

print('data prepared')


data prepared


In [3]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()

start = time.time()
lr.fit(X_train, y_train)
print('training completed in %s seconds'%(time.time() - start))

start = time.time()
y_pred = lr.predict(X_test)
print('prediction completed in %s seconds'%(time.time() - start))

cm = confusion_matrix(y_test, y_pred)

print(cm)


D:\Users\onur\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


training completed in 2.598599910736084 seconds
prediction completed in 0.00797724723815918 seconds
[[93811    14]
 [   64    98]]


In [4]:
from sklearn.svm import SVC

svc = SVC(kernel='rbf')

start = time.time()
svc.fit(X_train, y_train)
print('training completed in %s seconds'%(time.time() - start))

start = time.time()
y_pred = svc.predict(X_test)
print('prediction completed in %s seconds'%(time.time() - start))

cm = confusion_matrix(y_test, y_pred)

print(cm)


training completed in 196.6151580810547 seconds
prediction completed in 14.447367429733276 seconds
[[93818     7]
 [   57   105]]


In [5]:
from sklearn.svm import SVC

svc = SVC(kernel='poly')

start = time.time()
svc.fit(X_train, y_train)
print('training completed in %s seconds'%(time.time() - start))

start = time.time()
y_pred = svc.predict(X_test)
print('prediction completed in %s seconds'%(time.time() - start))

cm = confusion_matrix(y_test, y_pred)

print(cm)


training completed in 47.84837198257446 seconds
prediction completed in 1.8719923496246338 seconds
[[93810    15]
 [   43   119]]


In [6]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

start = time.time()
gnb.fit(X_train, y_train)
print('training completed in %s seconds'%(time.time() - start))

start = time.time()
y_pred = gnb.predict(X_test)
print('prediction completed in %s seconds'%(time.time() - start))

cm = confusion_matrix(y_test, y_pred)

print(cm)


training completed in 0.16184711456298828 seconds
prediction completed in 0.08710527420043945 seconds
[[91803  2022]
 [   26   136]]


In [8]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(criterion='entropy')

start = time.time()
dt.fit(X_train, y_train)
print('training completed in %s seconds'%(time.time() - start))

start = time.time()
y_pred = dt.predict(X_test)
print('prediction completed in %s seconds'%(time.time() - start))

cm = confusion_matrix(y_test, y_pred)

print(cm)
    

training completed in 7.826209306716919 seconds
prediction completed in 0.015512228012084961 seconds
[[93790    35]
 [   36   126]]


In [13]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(n_estimators=3, criterion='entropy')

start = time.time()
rfc.fit(X_train, y_train)
print('training completed in %s seconds'%(time.time() - start))

start = time.time()
y_pred = rfc.predict(X_test)
print('prediction completed in %s seconds'%(time.time() - start))

cm = confusion_matrix(y_test, y_pred)

print(cm)


training completed in 3.489541530609131 seconds
prediction completed in 0.03062725067138672 seconds
[[93812    13]
 [   45   117]]


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=1, metric='minkowski')

start = time.time()
knn.fit(X_train, y_train)
print('training completed in %s seconds'%(time.time() - start))

start = time.time()
y_pred = knn.predict(X_test)
print('prediction completed in %s seconds'%(time.time() - start))

cm = confusion_matrix(y_test, y_pred)

print(cm)
